### PR TITLE
Set app cache directory for linux

### PR DESCRIPTION
**Pull request by anidotnet**

### CODE REVIEW

**Comment by elexx** [comment]
I just wanted to push my PR to fix this TODO, when I noticed yours. A basically did the same you did, with a small difference:
How about moving the cache directory to `$HOME/.cache/`? This would be [the suggested default](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) if no `$XDG_CACHE_HOME` is set. And it would not add another folder to the userhome.

Also from my observation during the last years more and more applications are moving towards putting their configs to `$HOME/.config/appname`, their caches to `$HOME/.cache/appname` and if it's a user-land installation their binary to `$HOME/.local/bin/`.

**Comment by mikehearn** [comment]
Thanks! I'll merge this but isn't the current standard on Linux that caches go under ~/.config rather than at the top level?

**Comment by mikehearn** [comment]
Ah! I had this tab open since this morning but only replied now so I didn't see your comment.

Yes, I agree, putting it under ~/.caches sounds like the way to go - bonus points if you check the environment variable first.

**Comment by anidotnet** [comment]
@mikehearn here you go

**Comment by mikehearn** [comment]
Excellent! Thanks! And @elexx - sorry for the duplication of work. Let's get into the habit of announcing what we're working on in Slack, I'm not so good at this myself but I'll try to do it.

**Comment by elexx** [comment]
Never mind!
Yes, announcing on Slack or opening an issue and self-assigning it would be a big benefit I guess.

**Pull request merged**
