### PR TITLE
Bootstrap for linux

### PR DESCRIPTION
**Pull request by anidotnet**

### CODE REVIEW

**Comment by mikehearn** [comment]
Thanks, this looks very reasonable. I'm installing the latest Ubuntu to try it out.

That said, given that snappy appears to offer the same features the bootstrap is trying to obtain, I'm still not sure we should be doing our own online update engine for Linux these days. Seems like snappy works on most distros?

**Comment by mikehearn** [comment]
On the other hand, on further investigation, maybe snap isn't so ideal after all ...

**Comment by mikehearn** [comment]
On the other hand, on further investigation, maybe snap isn't so ideal after all ...

**Comment by mikehearn** [comment]
Thanks for the contribution! I modified the packageLinux task to make a deb, as the 'native' type wasn't recognised or doing anything. It works! Graviton appears in the application menu in Ubuntu, albeit with an ugly low res icon, and starting it opens the app. We need to adjust the layout slightly to make it look right on Linux too, but otherwise, no problems! "Wrote once, ran it everywhere!"

**Comment by anidotnet** [comment]
Awesome

**Pull request merged**
