### PR TITLE
Retry with reversed groupId if coordinates not found (GUI)

### LINKED ISSUE #22: If coordinates are not found, reverse the components and try again
Right now you start an app in Graviton by specifying a Maven coordinate. There is some smartness done to make it easier:

* `com.github.spotbugs:spotbugs` without a version will select the latest version
* `com.github.spotbugs` will assume the artifact is the same as the last groupID component

But reverse DNS is a bit odd for people who aren't programmers and are used to things being the other way around. Allow apps to be started with DNS style names by reversing the components if the first attempt isn't found, then trying again:

`spotbugs.github.com` -> `com.github.spotbugs`

`tictactoe.plan99.net` -> `net.plan99.tictactoe`

### PR DESCRIPTION
**Pull request by belu**
This PR fixes #22 for the GUI.

### CODE REVIEW

**Comment by mikehearn** [comment]
Pretty good but I think the GUI may be the wrong place to put it - why not put that logic inside AppLauncher, that way the command line will get it too and we'll be consistent in how we handle coordinates.

**Comment by belu** [comment]
@mikehearn Will move the logic to AppLauncher.

**Comment by belu** [comment]
@mikehearn The retry logic is now in `AppLauncher.download`. Now it works for the GUI and the CLI.

**Comment by mikehearn** [comment]
Looks good, thanks!

**Pull request merged**
